export const ANIMAL_BREEDS: Record<string, string[]> = {
  Dog: [
    'Affenpinscher',
    'Afghan Hound',
    'Airedale Terrier',
    'Akita',
    'Alaskan Malamute',
    'American Bulldog',
    'American Pit Bull Terrier',
    'American Staffordshire Terrier',
    'Australian Cattle Dog', 'Australian Shepherd',
    'Basenji',
    'Basset Hound',
    'Beagle',
    'Bearded Collie',
    'Bernese Mountain Dog',
    'Bichon Frise',
    'Bloodhound',
    'Border Collie',
    'Border Terrier',
    'Borzoi',
    'Boston Terrier',
    'Boxer',
    'Boykin Spaniel',
    'Brittany',
    'Bull Terrier',
    'Bulldog',
    'Bullmastiff',
    'Cairn Terrier',
    'Cane Corso',
    'Cavalier King Charles Spaniel',
    'Chesapeake Bay Retriever',
    'Chihuahua',
    'Chinese Crested',
    'Chinese Shar-Pei',
    'Chow Chow',
    'Cocker Spaniel',
    'Collie',
    'Dachshund',
    'Dalmatian',
    'Doberman Pinscher',
    'Dogo Argentino',
    'English Cocker Spaniel',
    'English Setter',
    'English Springer Spaniel',
    'French Bulldog',
    'German Shepherd',
    'German Shorthaired Pointer',
    'Giant Schnauzer',
    'Golden Retriever',
    'Great Dane',
    'Great Pyrenees',
    'Greyhound',
    'Havanese',
    'Irish Setter',
    'Irish Wolfhound',
    'Italian Greyhound',
    'Jack Russell Terrier',
    'Japanese Chin',
    'Labrador Retriever',
    'Lhasa Apso',
    'Maltese',
    'Mastiff',
    'Miniature Pinscher',
    'Miniature Schnauzer',
    'Newfoundland',
    'Norwegian Elkhound',
    'Old English Sheepdog',
    'Papillon',
    'Pekingese',
    'Pembroke Welsh Corgi',
    'Pomeranian',
    'Poodle',
    'Portuguese Water Dog',
    'Pug',
    'Rat Terrier',
    'Rhodesian Ridgeback',
    'Rottweiler',
    'Saint Bernard',
    'Samoyed',
    'Schipperke',
    'Scottish Terrier',
    'Shetland Sheepdog',
    'Shiba Inu',
    'Shih Tzu',
    'Siberian Husky',
    'Staffordshire Bull Terrier',
    'Standard Schnauzer',
    'Vizsla',
    'Weimaraner',
    'West Highland White Terrier',
    'Whippet',
    'Yorkshire Terrier',
    'Otra'
  ],
  Cat: [
    'Abisinio',
    'American Curl',
    'American Shorthair',
    'Angora Turco',
    'Azul Ruso',
    'Balinés',
    'Bengala',
    'Birmano',
    'Bombay',
    'British Shorthair',
    'Burmés',
    'Chartreux',
    'Cornish Rex',
    'Devon Rex',
    'Egyptian Mau',
    'Exótico de Pelo Corto',
    'Himalayo',
    'Javanés',
    'Khao Manee',
    'Korat',
    'Kurilian Bobtail',
    'LaPerm',
    'Maine Coon',
    'Manx',
    'Munchkin',
    'Neva Masquerade',
    'Noruego de Bosque',
    'Ocicat',
    'Oriental',
    'Persa',
    'Peterbald',
    'Ragdoll',
    'Savannah',
    'Scottish Fold',
    'Selkirk Rex',
    'Siamés',
    'Siberiano',
    'Singapura',
    'Snowshoe',
    'Somali',
    'Sphynx',
    'Tonkinés',
    'Toyger',
    'Van Turco',
    'Otra'
  ],
  Other: [
    'No aplica',
    'Otra'
  ]
};
